### ISSUE TITLE
Adopt pyproject.toml

### ISSUE THREAD

**Issue by stefnotch** [cg-tuwien/ppsurf_modeling#2]
This project currently uses a `requirements.txt` file for specifying dependencies, and politely tells us students to create a virtual environment.
That is absolutely the correct way of doing it today. 🎉 

However, the `requirements.txt` file comes with a number of shortcomings (main one being that there's no separation between "dependencies that I'm using" and "dependencies of dependencies")[^1].

The Python world is currently fixing this, by very recently having adopted
- [`pyproject.toml`](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/): Direct dependencies and Python version go in here.
- [PEP 751, a standardized lockfile](https://peps.python.org/pep-0751/): *All* dependencies, with their *exact* versions go in here. This was adopted less than a month ago!

Those files are currently being implemented in the various Python package managers. Notably
- UV implements them today https://github.com/astral-sh/uv/issues/12584
- Pip is going to implement them https://github.com/pypa/pip/issues/13334

With that in mind, I would love it if eventually, we would be using a `pyproject.toml` in this repository!

### Big Limitation

One of the dependencies is no longer in active development, and does not work with the new `pyproject.toml` standard. It seems like it won't ever be updated.
https://github.com/rusty1s/pytorch_cluster/issues/185

### Tangential Note
On that note, if you haven't tried out [uv](https://github.com/astral-sh/uv) for Python, I can wholeheartedly recommend it. It's super fast, implements official Python standards, and automatically creates virtual environments. ✨ 

With that, the whole step instructions in the Readme can be shortened down to:
> 2. Install [UV](https://docs.astral.sh/uv/)
> 3. Install all necessary dependencies with `uv sync`
> 4. Run the code with `uv run make_dataset.py` (or select the interpreter in Pycharm, as per usual)

[^1]: If that dependency management stuff doesn't immediately make sense, I'm happy to properly explain it.

**Comment by stefnotch** [comment]
By the way, here's the `pyproject.toml` that I am using for the first two parts of the exercise. The final part currently does not work. :(

```toml
[project]
dependencies = [
    "Levenshtein==0.27.1",
    "jsonargparse[signatures]>=4.27.7",
    "matplotlib==3.10.1",
    "numpy==2.2.3",
    "openpyxl==3.0.9",
    "overrides==7.7.0",
    "pandas==2.2.3",
    "pykdtree==1.4.1",
    "pysdf==0.1.9",
    "pytorch-lightning==2.4.0",
    "rtree>=1.4.0",
    "scipy==1.15.2",
    "tensorboard==2.19.0",
    "torch==2.4.1",
    "torchvision==0.19.1",
    "tqdm==4.67.1",
    "trimesh==4.6.4",
    "xmlschema==3.4.3",
]
name = "ppsurf-modeling"
requires-python = "==3.12.*"
version = "0.1.0"
[[tool.uv.index]]
explicit = true
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"

[tool.uv.sources]
torch = [
    { index = "pytorch-cu124", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu124", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
```

Pytorch is sadly a bit of a special case, and needs some bonus configuring. Currently I did the UV-specific way of configuring it, and didn't look into how Poetry, Pip, etc would configure it.

And since I am on Windows, I had to install PySDF by editing it and then doing `uv pip install pysdf-0.1.9.tar.gz`
